### ISSUE TITLE
Import `.default` by default

### ISSUE THREAD

**Issue by SaFrMo** [funkhaus/vuepress#103]
Right now we need to do a lot of

`require('thing-to-require').default`

We should find a way to import `default` automatically!

**Comment by drewbaker** [comment]
+1 to this!

**Comment by johndigital** [comment]
So this was actually only an issue with fh-components, because of the way each component was getting bundled in webpack. It has now been fixed in https://github.com/funkhaus/fh-components/commit/9d65e32f4e3a6da549843fe7048fc11be90b1760, however it **will** break old sites if you upgrade!

With the new change, both of these methods of importing a component now work great and will get you the same exact result:
```js
import someComponent from 'fh-components/some-component'
const someComponent = require('fh-components/some-component')
```

However, this way of importing will **NOT** work and will get you `undefined`
```js
const someComponent = require('fh-components/some-component').default
```
