### ISSUE TITLE
Change modular-menu names and fix classes

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#12]
Lets change `modular-menu` to be `wp-menu` and we try to match the default WordPress class names, like `has-sub-menu`, `current-menu-item`, 'menu-item', 'current-item-ancestor' etc.

**Comment by SaFrMo** [comment]
@drewbaker @jrobson153 @lwaldner I used [this page](https://developer.wordpress.org/reference/functions/wp_nav_menu/) in the WordPress docs to determine which classes to add. 

I skipped the `object` post type/taxonomy declarations, since we seem to use those a bit less frequently and they'd be pretty easy to set up on a later install if needed - set up another issue if I should add them or anything else in. Thanks!

**Comment by SaFrMo** [comment]
Fix was added in c386f8a8 and 62643530, fyi
