### ISSUE TITLE
Change the way menu names work

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#13]
Ideally you call a menu component by doing this:

`<wp-menu name="Main Menu" class="menu main-menu"></wp-menu>`

**Comment by drewbaker** [comment]
Also, should not be a `div` wrapping the `ul`

**Comment by SaFrMo** [comment]
* Removed `<div>` wrapper
* Changed globally-registered component name to `wp-menu`
* Changed `slug` prop to `name`, menu now searches for name instead of slug
* Changed `ModulerMenu.vue` to `WpMenu.vue`
* Added some default WordPress menu classes to menu-items

All in a593958 - continuing work on this in #12
