### ISSUE TITLE
Moving the fh-deploy queue to package.json

### ISSUE THREAD

**Issue by jrobson153** [funkhaus/vuepress#68]
It would be great if the "queue" array that's required by the fh-deploy config file could be in version control. That queue only needs to change when new files are added or removed, and it's a huge pain to have to rebuild it when you're cloning a project. 

It doesn't make sense to have 2 different files, one for credentials that will be gitignored and one for a queue that will be tracked, but maybe it makes sense for fh-deploy to look at the ["files" property](https://docs.npmjs.com/files/package.json#files) in the package.json file rather than its own config file?

That property is primarily used to tell npm how to publish a package, but I think it generally makes sense for our use case since our version of "publishing" is just pushing to a Wordpress server.

This obviously would be mostly a change to the fh-deploy package, but we would have to make changes in this repo as well.

@SaFrMo thoughts?

**Comment by SaFrMo** [comment]
Yep, I like that a lot! This way, the .deployrc file will just be login credentials, which makes perfect sense. I'll make the changes to fh-deploy first, then update here. Great note!

**Comment by SaFrMo** [comment]
Fixed in f006a8d!

No examples are included, duplicated, renamed, etc. any more because they're not needed. The first time you run `npm run deploy`, you'll be prompted for some information that automatically creates a config file for you, which is .gitignored and uses the files in the `package.json` `files` property by default. This should remove the need for any manual setup of login credentials.

Marking closed - let me know if there are any questions!
