### ISSUE TITLE
Self closing componets from shortcodes don't render following text

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#81]
If I have a chunk of text like this in the WP content editor:

```
<h2>Say Hello</h2>

[social-links]

We have five regional o ces throughout California in order to provide superior service o erings. Reach out to us today to get started on your project.
```
And this PHP with a self closing component:

```
	function custom_shortcode_social_links( $atts, $content = '', $name ) {
            // return '<social-links/>'; // This won't render any content below the shortcode
            return '<social-links></social-links>'; // This will render content below shortcode.
	}
	add_shortcode( 'social-links', 'custom_shortcode_social_links' );
```

The shortcode will work, but not show any text below it.

**Comment by jrobson153** [comment]
@drewbaker I ran into this today, here's the answer: https://vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended

The big takeaway:
> Components with no content should be self-closing in single-file components, string templates, and JSX - but never in DOM templates.

It's okay (and recommended) for us to do self-closing tags in single file components because they're pre-compiled but since `wp-content` compiles them on the fly, self-closing tags break things.

Basically, the answer is just don't do this in shortcodes.
