### ISSUE TITLE
Improve deploy when json file is missing

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/vuepress#90]
When running `npm run deploy`, but without a `.deployrc.json` file in the repo, I think the ideal scenario is that the `.deployrc.json` file is created for you in the repo root, and you are prompted to config that file and run `npm run deploy` again. The current solution were it just prompts you for each setting actually work because of the missing queue settings, so it seems sort of useless.

I think the default file should include all of the things we need for the default Funkhaus Vuepress theme (so queue and target setup as best we can). If you leave the username/password empty, then it should prompt you to enter them each time `npm run deploy` is run.

Something like this:
```
module.exports = {
    settings: {
        "host": "sftp.flywheelsites.com",
        "port": "22",
        "username": "", // Leave this empty if you want to be prompted each time.
        "password": "" // Leave this empty if you want to be prompted each time. 
    },
    queue: [
        "functions/**/*.*",
        "parts/**/*.*",
        "static/**/*.*",
        "functions.php",
        "index.php",
        "style.css",
        "screenshot.png"
    ],
    target: "/org-funkhaus/{SITE NAME HERE}/wp-content/themes/{THEME NAME HERE}"
}
```

**Comment by SaFrMo** [comment]
The current solution already includes the `queue` in your example in `package.json`'s `files` - see [here](https://github.com/funkhaus/vuepress/blob/master/package.json#L10-L18). If no queue is defined in the `deployrc.json` file, fh-deploy will fall back to package.json's `files`, so fh-deploy will work out of the box after you complete the initial config.

I think it wasn't working for you on the Bernards site because it was based on an older version of Vuepress that didn't have the `files` defined in package.json.

> I think the default file should include all of the things we need for the default Funkhaus Vuepress theme 
When you say "default file," do you mean the contents of the Vuepress repo? I didn't want to include the host or target directory since this is a public repo and I didn't want to make our FTP structure public.

I can make the username like the password where if it's missing in the config file, you have to enter it manually when running `fh-deploy` - I'll raise an issue on the fh-deploy repo for that.

Let me know if this doesn't answer your questions or you see any other issues!

**Comment by johndigital** [comment]
I think having the username behave like the password where it will prompt you is a good idea. I also agree that when fh-deploy walks you through the configuration it should not attempt to deploy immediately after, that seems like it could be dangerous if you haven't gotten a chance to set up the files declaration. Not sure if it behaves that way currently, but I'll raise an issue in fh-deploy about it.

Otherwise I think everything else is pretty good as is. I don't think it will be that smart or beneficial to have fh-deploy assume flywheel credentials and server structure because it's just a generic tool meant to work with any sftp. If we feel like we really need that feature we will want to do it in vuepress, and the easiest way would probably just be by checking in a `.deployrc.json` file with those starting values.

Having the vuepress default  files already declared is definitely helpful for convenience, and as Sander mentioned that is already implemented in the latest version.

I think this is good to be closed, but @drewbaker feel free to re-open if you think there are more changes that need to happen here.
